Auth setup
WildCodeSchool/p3-g3-sept21-lille-retrofit-backend pull request #1
Opened 2021-12-28 14:25 UTC by NacymeG

2022-01-05 13:30 UTC, Caroline-CD approved these changes
Some small modifications.

2022-01-05 13:30 UTC, Caroline-CD commented on db-config.js
> +const connection = mysql.createConnection({
It is possible to lighten the code for to avoid much process.env no ?

2022-01-05 13:30 UTC, Caroline-CD commented on models/auth.js
> +    repeadPass: Joi.ref('password'),
There is a little mistake here : repeatPass and no repeadPass

2022-01-05 13:30 UTC, Caroline-CD commented on routes/auth.js
> +    console.log('Cookies: ', req.headers.cookie.split('=')[1]);
It will be necessary to remove the console.log

2022-01-05 14:23 UTC, LoicBrassart commented
@Caroline-CD If you spot changes to do, don't approve the PR ;-)

2022-01-05 15:36 UTC, Caroline-CD requested changes
Sorry, there are small modifications to be made

2022-01-10 09:15 UTC, Caroline-CD approved these changes
Ok :crystal_ball:

2022-01-10 09:57 UTC, Hacene010 approved these changes
it seems ok for me but why didn't you use passport ?

2022-01-10 10:07 UTC, NacymeG commented
> it seems ok for me but why didn't you use passport ?

The next PR will focus on the refactoring of authentication and passport implementation.

2022-01-10 10:41 UTC, merged