Form mailer
WildCodeSchool/p3-g3-sept21-lille-retrofit-backend pull request #10
Opened 2022-01-26 16:13 UTC by Caroline-CD

2022-01-26 16:23 UTC, NacymeG submitted a review, later dismissed
Ok for me 🥇

2022-01-26 16:27 UTC, Hacene010 requested changes

2022-01-26 16:27 UTC, Hacene010 commented on .env.sample
> +
empty line !

2022-01-26 16:27 UTC, Hacene010 commented on routes/contact.js
> +      else console.log(info);
Avoid to console log information

2022-01-27 09:01 UTC, NacymeG approved these changes
Ok for me !

2022-01-27 09:29 UTC, Hacene010 approved these changes

2022-01-27 10:17 UTC, merged