Debugging
WildCodeSchool/p3-g3-sept21-lille-retrofit-backend pull request #5
Opened 2022-01-17 13:22 UTC by NacymeG

2022-01-18 09:11 UTC, Morel-Victor approved these changes, later dismissed
Ok with fix

2022-01-18 14:38 UTC, Hacene010 requested changes
Plz fix the evils into the previous PR to not read the same things a lot of times :-)

2022-01-18 15:03 UTC, Hacene010 requested changes

2022-01-18 15:03 UTC, Hacene010 commented on routes/localisation.js
>      res.json(location);
Forgot the status :)

2022-01-18 15:06 UTC, Hacene010 submitted a review, later dismissed

2022-01-18 16:02 UTC, Morel-Victor approved these changes, later dismissed

2022-01-18 16:06 UTC, Morel-Victor approved these changes

2022-01-19 15:38 UTC, Hacene010 approved these changes

2022-01-20 22:45 UTC, merged